keep track of the direct cause of RetryError
 logging may not be enabled by using raise RetryError("max retry exceeded") from e
 we can get some usefull output from the exception handler:

ZeroDivisionError: division by zero

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "rdec_test-01.py", line 33, in <module>
    raise e
  File "rdec_test-01.py", line 31, in <module>
    print ("{} / {} = {}".format(i, i, rdiv_by(i)))
  File "/home/ali/git.unipart.io/pgcrt/openstack/rdec.py", line 36, in wrapped_func
    raise RetryError("max retry exceeded") from e
rdec.RetryError: max retry exceeded